# fly.toml app configuration file generated for theproshop on 2023-06-26T22:37:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "theproshop"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
source="product_images"
destination="/uploads"